<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Remove="Common\**" />
    <EmbeddedResource Remove="Enums\**" />
    <EmbeddedResource Remove="Exceptions\**" />
    <None Remove="Common\**" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
    <Folder Include="Entities\" />
    <Folder Include="Interfaces\Repositories\" />
  </ItemGroup>

</Project>

